title: Fyne Apps
email: info@fyne.io
url: "https://apps.fyne.io"

remote_theme: gdgmanagua/jekyll-mdl

header_type: default
post_type: highlight

disqus: true
disqus_shortname: 'fyne-apps'

more_vert:
  option1:
    name: Submit App
    link: mailto:info@fyne.io

collections:
  apps:
    output: true

defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

